### ISSUE TITLE
Plugin doesnt work

### ISSUE THREAD

**Issue by uehlbran** [fsantiag/sonar-clojure#28]
**Describe the bug**
I've tried running SonarQube versions (6.7.6, 7.0, 7.1, and 7.4) and none of the information from this plugin is reaching SonarQube. I've tried multiple Clojure libraries, and tons of different build options, but nothing changes. Your instructions appear to be out of date, but I'm not sure this is really a big issue. Most of those libraries you recommend are ether broken, have changed or some other variation that is causing issues, but after digging through conf files and error reports for the past 2 days I resolved those issues (not your fault of course). However, no information is still reaching SonarQube.

**How to reproduce**
Follow your directions on a fresh install of sonarqube.

**Expected behavior**
I expected it to actually show things like lines of code and other information. The normal stuff. It did not :(.

**Comment by fsantiag** [comment]
Hi @uehlbran, I am sorry to hear that you faced these issues in the past days. Could you specifically point what libraries/version you used and some sample of the source code you were trying to scan? 
Keep in mind that in order for SonarClojure to work, each one of the plugins need to run fine on your source code.

In the mean time, I will revisit the docs and see if left some loose ends.

**Comment by uehlbran** [comment]
So I tried multiple versions of the libraries that the docs say to include.
I tried the ones that are specifically listed and I tried the most up to
date versions.

[lein-codox "0.10.3"
[joanse/eastwood "0.3.5"]
[lein-kibit "0.1.6"]
[lein-ancient "0.6.15"]
[lein-cloverage "1.1.1"]
[lein-nvd "1.0.0"]

As far as source I just tried multiple clojure libraries such as: Ring,
Compojure, and Reagent. Clojure libraries are the only ones that never get
their data populated in SonarQube.

It appears that if I manually run eastwood it has a subprocess that fails.
When I run kibit it works fine. When I run lein ancient help it works fine
as well. NVD works completely fine. Cloverage also runs just fine. Finally,
codox also runs just fine. So it appears that the only one of those
libraries with issues is eastwood I suppose.

**Comment by uehlbran** [comment]
However, I just looked and the issue with eastwood is completely normal and
only results if you have exceptions or warnings. All of these libraries
have warning, but no exceptions. Therefore, since every library runs just
fine the issue has to be with the sonar-clojure plugin.

I have no clue what the issue could be though. Like I said earlier I've
tried SonarQube versions 6.7.6, 7.0, 7.1, and 7.4 and it is never populated
with any information when it comes to clojure libraries.

**Comment by uehlbran** [comment]
Here is my sonar-scanner output:

sudo /opt/sonar-scanner/bin/sonar-scanner
INFO: Scanner configuration file:
/opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file:
/var/lib/jenkins/workspace/Compojure/sonar-project.properties
INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Linux 4.15.0-46-generic amd64
INFO: User cache: /root/.sonar/cache
INFO: SonarQube server 7.1.0
INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is
platform dependent)
INFO: Publish mode
INFO: Load global settings
INFO: Load global settings (done) | time=36ms
INFO: Server id: 49B321BC-AWnAumkqQ9smpfoplzat
INFO: User cache: /root/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=72ms
INFO: Load/download plugins
INFO: Load/download plugins (done) | time=11ms
INFO: Process project properties
INFO: Execute project builders
INFO: Execute project builders (done) | time=2ms
INFO: Load project repositories
INFO: Load project repositories (done) | time=5ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=14ms
INFO: Load active rules
INFO: Load active rules (done) | time=227ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=10ms
INFO: Project key: Compojure
INFO: Project base dir: /var/lib/jenkins/workspace/Compojure
INFO: -------------  Scan Compojure
INFO: Base dir: /var/lib/jenkins/workspace/Compojure
INFO: Working dir: /var/lib/jenkins/workspace/Compojure/.scannerwork
INFO: Source paths: src, project.clj
INFO: Source encoding: UTF-8, default locale: en_US
INFO: Load server rules
INFO: Load server rules (done) | time=31ms
INFO: Index files
INFO: 7 files indexed
INFO: Quality profile for clj: Sonar way
INFO: Sensor SonarJavaXmlFileSensor [java]
INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=1ms
INFO: Sensor HTML [web]
INFO: Sensor HTML [web] (done) | time=7ms
INFO: Sensor SonarClojure [clojure]
INFO: Clojure project detected
INFO: Running Eastwood
WARN: Eastwood resulted in empty output
INFO: Saving issues
INFO: Sensor SonarClojure [clojure] (done) | time=29ms
INFO: Sensor SonarClojureKibit [clojure]
INFO: Running Kibit
INFO: Saving issues
INFO: Sensor SonarClojureKibit [clojure] (done) | time=8ms
INFO: Sensor SonarClojureAncient [clojure]
INFO: Running Lein Ancient
INFO: Sensor SonarClojureAncient [clojure] (done) | time=8ms
INFO: Sensor SonarClojureCloverage [clojure]
INFO: Running Cloverage
WARN: Cloverage report does not exists. Have you added added
target/coverage/codecov.json to
sonar.clojure.cloverage.json-output-location?
INFO: Sensor SonarClojureCloverage [clojure] (done) | time=7ms
INFO: Sensor SonarClojureLeinNvd [clojure]
INFO: Running Lein NVD
INFO: Sensor SonarClojureLeinNvd [clojure] (done) | time=24ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=4ms
INFO: Sensor CPD Block Indexer
INFO: Sensor CPD Block Indexer (done) | time=0ms
INFO: SCM Publisher is disabled
INFO: Calculating CPD for 0 files
INFO: CPD calculation finished
INFO: Analysis report generated in 61ms, dir size=54 KB
INFO: Analysis reports compressed in 7ms, zip size=17 KB
INFO: Analysis report uploaded in 164ms
INFO: ANALYSIS SUCCESSFUL, you can browse
http://134.50.75.53:9000/dashboard/index/Compojure
INFO: Note that you will be able to access the updated dashboard once the
server has processed the submitted analysis report
INFO: More about the report processing at
http://134.50.75.53:9000/api/ce/task?id=AWnPZCdQQePfkSptrUau
INFO: Task total time: 1.788 s
INFO:
------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO:
------------------------------------------------------------------------
INFO: Total time: 2.582s
INFO: Final Memory: 20M/402M
INFO:
------------------------------------------------------------------------

**Comment by uehlbran** [comment]
I was able to fix the warning in the above output by using lein cloverage
--codecov.

Now I can see coverage in sonarqube, but I still dont get any other
information such as lines of code, duplicates, bugs etc.

**Comment by uehlbran** [comment]
It seems like a lot of the issues are ultimately a byproduct of cloverage
and eastwood. Cloverage being extremely unstable, buggy, and prone to
crashing on almost everything. Eastwood being a bit less picky, but still
not providing much information at all.

sonar-clojure also doesn;t run the appropriate libraries correctly. It has
missing flags for cloverage specifically the --codecov flag. IT also
doesn't seem to run the individual libraries on its like nvd, kibit,
cloverage, and well all of them. This has to be done manually to work.

No matter what I'm still missing tons of information such as lines of code
across all projects and none of the graphs ever show any information.

**Comment by fsantiag** [comment]
I just followed the instructions provided in the README file and I was able to make SonarClojure work for Compojure. I can see code smells, coverage, vulnerabiltiies, etc. I also tried to disable the plugins when necessary and it worked.
The only thing I had to change was the version of some of the plugins and that is why I just updated the documentation with this information. I also included a note to remind users that plugins need to run fine individually in order to SonarClojure to parse the results. :)
![Screenshot from 2019-03-30 21-18-16](https://user-images.githubusercontent.com/13712202/55283091-64bb2500-5331-11e9-8874-2ee8ca6b9d02.png)

However, I tested with Ring and Reagent and I faced some issues, similar to what you are describing and here are my thoughts:
1. If eastwood throws an exception, it stops linting. I think we can try to by pass that using `{:continue-on-exception true}`. The PR #27 addresses that but we might need to extend this functionality to other plugins.
2.  Cloverage indeed is the least stable plugin. If the project is complex or simply has a different folder structure, Cloverage will likely fail but you still can try to tweak the command line arguments for cloverage to make it work for your project. Some of the issues are related to folder structure, namespaces, etc. (At the moment this is not possible using SonarClojure but the it should be soon)
3. You will see that most of the problems are related to the plugins and that is a bit out of my control. At the end of the day, if you can't make the plugin work for your project, you will have to disable it.

Overall, I agree that some of the plugins might not provide the best stability. Some might just crash during execution or simply not work at all for your project. However we can't do much about it for now. Those were the plugins that I could find so far. If you have better options, please let me know. We can try to enable them on SonarClojure.

Regarding the missing flags and other issues, as I said, I was able to use the plugin fine. You can see that we are using the `--codecov` flag [here](https://github.com/fsantiag/sonar-clojure/blob/master/src/main/java/org/sonar/plugins/clojure/sensors/cloverage/CloverageSensor.java#L23).
What version of SonarClojure you installed on your server?

**Comment by uehlbran** [comment]
Weird. I don't know why it's giving me so many issues. I'm running the
latest version of sonar-clojure 1.4.0. I also have multiple instances of
SonarQube running: 6.7.6, 7.0, 7.1, and 7.4. All of which basically have
the same issues. For me, it never generates the code coverage file though.
Regardless of project, version of sonarqube, and so-on. I always have to
manually run cloverage with that flag for it to work...

Unfortunately, I don't know what else I can say or provide to clear this
up. I also don't know of any other libraries that exist that would be more
stable/compatible. At this point, I might just have to go the route of
leaving Clojure out of this or creating what I need from scratch I suppose.

**Comment by fsantiag** [comment]
Could you share with me:

1. Your `sonar-project.properties`.
2. The project you are trying to run SonarClojure.
3. Version of SonarQube you would like to use.

I can try to run on my side with the same settings and see if I experience the same errors.

**Comment by fsantiag** [comment]
Hi @uehlbran, were you able to figure this out? If don't hear from you I will close this issue since I am not able to reproduce your problem.

**Comment by uehlbran** [comment]
I have not got it resolved. I've been dealing with some other work related issues, but I will post everything you requested tomorrow, Thursday. I appreciate your help!

**Comment by uehlbran** [comment]
Here is my sonar-project.properties files:


sonar.projectKey=CompojureTest

sonar.projectName=Compojure

sonar.projectVersion=0.8.1

sonar.sources=src,test,project.clj

sonar.clojure.lein-nvd.json-output-location=
target/nvd/dependency-check-report.json

sonar.clojure.cloverage.json-output-location=target/coverage/codecov.json


The project I'm trying to run is Clojure. The version of SonarQube I'd like
to use is 7.1.

**Comment by uehlbran** [comment]
Oops. I just noticed I had a typo in that last post. The project that I'm
trying to run is Compojure not Clojure haha. Everything else is correct
though.

**Comment by fsantiag** [comment]
Hi again @uehlbran, sorry for the late reply.

Here are my steps:
1. I started by cloning the compojure project: https://github.com/weavejester/compojure
2. I added the following `sonar-project.properties` to the project root directory (following what you provided me before)
```properties
sonar.projectKey=compojure
sonar.projectName=compojure
sonar.projectVersion=0.8.1
sonar.sources=src,test,project.clj
sonar.clojure.lein-nvd.json-output-location=target/nvd/dependency-check-report.json
sonar.clojure.cloverage.json-output-location=target/coverage/codecov.json
```
3. I added the required plugins to the compojure `project.clj` file and here is how the plugins section looks like:
```clj
  :plugins [[lein-codox "0.10.3"]
          [jonase/eastwood "0.3.5"]
          [lein-kibit "0.1.6"]
          [lein-ancient "0.6.15"]
          [lein-cloverage "1.1.1"]
          [lein-nvd "1.0.0"]]
```
4. I ran the sonnar-scanner version 3.3.0.1492 in the root directory.
5. The analysis data was published to my local Sonarqube instance (version 7.1) as you can see in the screenshot:
![Screenshot from 2019-05-02 19-59-20](https://user-images.githubusercontent.com/13712202/57112078-e7f6de80-6d14-11e9-9887-ab41a52bbdc5.png)

As far as I can see, the plugin seems to be working fine. We don't have duplication or bugs reported because we don't have those features yet. 
I am afraid I can't help you anymore since I am not able to reproduce your problem and you are the only one facing something like that.
